### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by streaps** [ASPLes/turbulence#1]
Will mod-python be ported to Python 3 or is this module stuck with Python 2.7 (which is unmaintained)?

**Comment by francisbrosnan** [comment]
Hello,
Just confirm there are no plans to port mod-python to python 3. We will be supporting turbulence (and libvortex-1.1 and libaxl) for python 2.7 as much as possible. We are about to release support for Debian Bullseye and we have full support for Ubuntu Focal. We expect to support Rocky Linux 8 and possible others as long as they provide minimal python 2.7, but our intention is to phase it out in the following years (as well as PyVortex and PyAxl).
Best Regards,

**Comment by streaps** [comment]
Thank you. That's very useful information.
